# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Victoria Ta\Desktop\INFO366\Project\INFO_366_Project\main\gui-add.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_windowAdd(object):
    def setupUi(self, windowAdd):
        windowAdd.setObjectName("windowAdd")
        windowAdd.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(windowAdd)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setGeometry(QtCore.QRect(610, 520, 75, 23))
        self.buttonSave.setObjectName("buttonSave")
        self.buttonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCancel.setGeometry(QtCore.QRect(700, 520, 75, 23))
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 761, 451))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelConcentration = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelConcentration.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelConcentration.setObjectName("labelConcentration")
        self.gridLayout_2.addWidget(self.labelConcentration, 7, 0, 1, 1)
        self.labelClasses = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelClasses.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelClasses.setObjectName("labelClasses")
        self.gridLayout_2.addWidget(self.labelClasses, 6, 0, 1, 1)
        self.labelAddSpell = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelAddSpell.setFont(font)
        self.labelAddSpell.setObjectName("labelAddSpell")
        self.gridLayout_2.addWidget(self.labelAddSpell, 0, 0, 1, 1)
        self.labelRange = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelRange.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelRange.setObjectName("labelRange")
        self.gridLayout_2.addWidget(self.labelRange, 4, 0, 1, 1)
        self.filterRange = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterRange.sizePolicy().hasHeightForWidth())
        self.filterRange.setSizePolicy(sizePolicy)
        self.filterRange.setMaximumSize(QtCore.QSize(125, 16777215))
        self.filterRange.setObjectName("filterRange")
        self.filterRange.addItem("")
        self.filterRange.setItemText(0, "")
        self.filterRange.addItem("")
        self.filterRange.addItem("")
        self.filterRange.addItem("")
        self.filterRange.addItem("")
        self.gridLayout_2.addWidget(self.filterRange, 4, 1, 1, 1)
        self.labelSchool = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelSchool.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelSchool.setObjectName("labelSchool")
        self.gridLayout_2.addWidget(self.labelSchool, 5, 0, 1, 1)
        self.labelRitual = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelRitual.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelRitual.setObjectName("labelRitual")
        self.gridLayout_2.addWidget(self.labelRitual, 8, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelName.setObjectName("labelName")
        self.gridLayout_2.addWidget(self.labelName, 1, 0, 1, 1)
        self.filterConcentration = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterConcentration.sizePolicy().hasHeightForWidth())
        self.filterConcentration.setSizePolicy(sizePolicy)
        self.filterConcentration.setMaximumSize(QtCore.QSize(60, 16777215))
        self.filterConcentration.setObjectName("filterConcentration")
        self.filterConcentration.addItem("")
        self.filterConcentration.setItemText(0, "")
        self.filterConcentration.addItem("")
        self.filterConcentration.addItem("")
        self.gridLayout_2.addWidget(self.filterConcentration, 7, 1, 1, 1)
        self.filterRitual = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterRitual.sizePolicy().hasHeightForWidth())
        self.filterRitual.setSizePolicy(sizePolicy)
        self.filterRitual.setMaximumSize(QtCore.QSize(60, 16777215))
        self.filterRitual.setObjectName("filterRitual")
        self.filterRitual.addItem("")
        self.filterRitual.setItemText(0, "")
        self.filterRitual.addItem("")
        self.filterRitual.addItem("")
        self.gridLayout_2.addWidget(self.filterRitual, 8, 1, 1, 1)
        self.labelDescription = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelDescription.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelDescription.setObjectName("labelDescription")
        self.gridLayout_2.addWidget(self.labelDescription, 2, 0, 1, 1)
        self.labelLevel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelLevel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelLevel.setObjectName("labelLevel")
        self.gridLayout_2.addWidget(self.labelLevel, 3, 0, 1, 1)
        self.filterDescription = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterDescription.sizePolicy().hasHeightForWidth())
        self.filterDescription.setSizePolicy(sizePolicy)
        self.filterDescription.setMaximumSize(QtCore.QSize(125, 16777215))
        self.filterDescription.setObjectName("filterDescription")
        self.gridLayout_2.addWidget(self.filterDescription, 2, 1, 1, 1)
        self.filterName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterName.sizePolicy().hasHeightForWidth())
        self.filterName.setSizePolicy(sizePolicy)
        self.filterName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filterName.setObjectName("filterName")
        self.gridLayout_2.addWidget(self.filterName, 1, 1, 1, 1)
        self.filterLevel = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLevel.sizePolicy().hasHeightForWidth())
        self.filterLevel.setSizePolicy(sizePolicy)
        self.filterLevel.setMaximumSize(QtCore.QSize(40, 16777215))
        self.filterLevel.setObjectName("filterLevel")
        self.filterLevel.addItem("")
        self.filterLevel.setItemText(0, "")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.gridLayout_2.addWidget(self.filterLevel, 3, 1, 1, 1)
        self.filterSchool = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterSchool.sizePolicy().hasHeightForWidth())
        self.filterSchool.setSizePolicy(sizePolicy)
        self.filterSchool.setMaximumSize(QtCore.QSize(125, 16777215))
        self.filterSchool.setObjectName("filterSchool")
        self.filterSchool.addItem("")
        self.filterSchool.setItemText(0, "")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.gridLayout_2.addWidget(self.filterSchool, 5, 1, 1, 1)
        self.filterClass = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterClass.sizePolicy().hasHeightForWidth())
        self.filterClass.setSizePolicy(sizePolicy)
        self.filterClass.setMaximumSize(QtCore.QSize(125, 16777215))
        self.filterClass.setObjectName("filterClass")
        self.filterClass.addItem("")
        self.filterClass.setItemText(0, "")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.gridLayout_2.addWidget(self.filterClass, 6, 1, 1, 1)
        self.labelComponents = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelComponents.sizePolicy().hasHeightForWidth())
        self.labelComponents.setSizePolicy(sizePolicy)
        self.labelComponents.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelComponents.setObjectName("labelComponents")
        self.gridLayout_2.addWidget(self.labelComponents, 9, 0, 1, 1)
        self.filterComponents = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterComponents.sizePolicy().hasHeightForWidth())
        self.filterComponents.setSizePolicy(sizePolicy)
        self.filterComponents.setMaximumSize(QtCore.QSize(125, 16777215))
        self.filterComponents.setObjectName("filterComponents")
        self.filterComponents.addItem("")
        self.filterComponents.setItemText(0, "")
        self.filterComponents.addItem("")
        self.filterComponents.addItem("")
        self.filterComponents.addItem("")
        self.filterComponents.addItem("")
        self.gridLayout_2.addWidget(self.filterComponents, 9, 1, 1, 1)
        windowAdd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(windowAdd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        windowAdd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(windowAdd)
        self.statusbar.setObjectName("statusbar")
        windowAdd.setStatusBar(self.statusbar)

        self.retranslateUi(windowAdd)
        QtCore.QMetaObject.connectSlotsByName(windowAdd)

    def retranslateUi(self, windowAdd):
        _translate = QtCore.QCoreApplication.translate
        windowAdd.setWindowTitle(_translate("windowAdd", "Add Spell"))
        self.buttonSave.setText(_translate("windowAdd", "Save"))
        self.buttonCancel.setText(_translate("windowAdd", "Cancel"))
        self.labelConcentration.setText(_translate("windowAdd", "Concentration"))
        self.labelClasses.setText(_translate("windowAdd", "Classes"))
        self.labelAddSpell.setText(_translate("windowAdd", "Add Spell"))
        self.labelRange.setText(_translate("windowAdd", "Range"))
        self.filterRange.setItemText(1, _translate("windowAdd", "Self"))
        self.filterRange.setItemText(2, _translate("windowAdd", "Touch"))
        self.filterRange.setItemText(3, _translate("windowAdd", "Sight"))
        self.filterRange.setItemText(4, _translate("windowAdd", "Special"))
        self.labelSchool.setText(_translate("windowAdd", "School"))
        self.labelRitual.setText(_translate("windowAdd", "Ritual"))
        self.labelName.setText(_translate("windowAdd", "Name"))
        self.filterConcentration.setItemText(1, _translate("windowAdd", "yes"))
        self.filterConcentration.setItemText(2, _translate("windowAdd", "no"))
        self.filterRitual.setItemText(1, _translate("windowAdd", "yes"))
        self.filterRitual.setItemText(2, _translate("windowAdd", "no"))
        self.labelDescription.setText(_translate("windowAdd", "Description"))
        self.labelLevel.setText(_translate("windowAdd", "Level"))
        self.filterLevel.setItemText(1, _translate("windowAdd", "0"))
        self.filterLevel.setItemText(2, _translate("windowAdd", "1"))
        self.filterLevel.setItemText(3, _translate("windowAdd", "2"))
        self.filterLevel.setItemText(4, _translate("windowAdd", "3"))
        self.filterLevel.setItemText(5, _translate("windowAdd", "4"))
        self.filterLevel.setItemText(6, _translate("windowAdd", "5"))
        self.filterLevel.setItemText(7, _translate("windowAdd", "6"))
        self.filterLevel.setItemText(8, _translate("windowAdd", "7"))
        self.filterLevel.setItemText(9, _translate("windowAdd", "8"))
        self.filterLevel.setItemText(10, _translate("windowAdd", "9"))
        self.filterSchool.setItemText(1, _translate("windowAdd", "Abjuration"))
        self.filterSchool.setItemText(2, _translate("windowAdd", "Conjuration"))
        self.filterSchool.setItemText(3, _translate("windowAdd", "Divination"))
        self.filterSchool.setItemText(4, _translate("windowAdd", "Enchantment"))
        self.filterSchool.setItemText(5, _translate("windowAdd", "Evocation"))
        self.filterSchool.setItemText(6, _translate("windowAdd", "Illusion"))
        self.filterSchool.setItemText(7, _translate("windowAdd", "Necromancy"))
        self.filterSchool.setItemText(8, _translate("windowAdd", "Transmutation"))
        self.filterClass.setItemText(1, _translate("windowAdd", "Bard"))
        self.filterClass.setItemText(2, _translate("windowAdd", "Cleric"))
        self.filterClass.setItemText(3, _translate("windowAdd", "Druid"))
        self.filterClass.setItemText(4, _translate("windowAdd", "Paladin"))
        self.filterClass.setItemText(5, _translate("windowAdd", "Ranger"))
        self.filterClass.setItemText(6, _translate("windowAdd", "Sorcerer"))
        self.filterClass.setItemText(7, _translate("windowAdd", "Warlock"))
        self.filterClass.setItemText(8, _translate("windowAdd", "Wizard"))
        self.labelComponents.setText(_translate("windowAdd", "Components"))
        self.filterComponents.setItemText(1, _translate("windowAdd", "no verbal"))
        self.filterComponents.setItemText(2, _translate("windowAdd", "no somatic"))
        self.filterComponents.setItemText(3, _translate("windowAdd", "no material"))
        self.filterComponents.setItemText(4, _translate("windowAdd", "no cost"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowAdd = QtWidgets.QMainWindow()
    ui = Ui_windowAdd()
    ui.setupUi(windowAdd)
    windowAdd.show()
    sys.exit(app.exec_())

