# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Victoria Ta\Desktop\INFO366\Project\INFO_366_Project\main\gui-pyqt5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.filterClass = QtWidgets.QComboBox(self.centralwidget)
        self.filterClass.setGeometry(QtCore.QRect(750, 100, 121, 21))
        self.filterClass.setObjectName("filterClass")
        self.filterClass.addItem("")
        self.filterClass.setItemText(0, "")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterClass.addItem("")
        self.filterSchool = QtWidgets.QComboBox(self.centralwidget)
        self.filterSchool.setGeometry(QtCore.QRect(620, 100, 121, 22))
        self.filterSchool.setObjectName("filterSchool")
        self.filterSchool.addItem("")
        self.filterSchool.setItemText(0, "")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterSchool.addItem("")
        self.filterRange = QtWidgets.QComboBox(self.centralwidget)
        self.filterRange.setGeometry(QtCore.QRect(490, 100, 121, 22))
        self.filterRange.setObjectName("filterRange")
        self.filterRange.addItem("")
        self.filterRange.setItemText(0, "")
        self.filterRange.addItem("")
        self.filterRange.addItem("")
        self.filterRange.addItem("")
        self.filterRange.addItem("")
        self.filterLevel = QtWidgets.QComboBox(self.centralwidget)
        self.filterLevel.setGeometry(QtCore.QRect(440, 100, 41, 22))
        self.filterLevel.setObjectName("filterLevel")
        self.filterLevel.addItem("")
        self.filterLevel.setItemText(0, "")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.filterLevel.addItem("")
        self.labelLevel = QtWidgets.QLabel(self.centralwidget)
        self.labelLevel.setGeometry(QtCore.QRect(440, 80, 41, 16))
        self.labelLevel.setObjectName("labelLevel")
        self.labelRange = QtWidgets.QLabel(self.centralwidget)
        self.labelRange.setGeometry(QtCore.QRect(490, 80, 41, 16))
        self.labelRange.setObjectName("labelRange")
        self.labelSchool = QtWidgets.QLabel(self.centralwidget)
        self.labelSchool.setGeometry(QtCore.QRect(620, 80, 41, 16))
        self.labelSchool.setObjectName("labelSchool")
        self.labelClasses = QtWidgets.QLabel(self.centralwidget)
        self.labelClasses.setGeometry(QtCore.QRect(750, 80, 41, 16))
        self.labelClasses.setObjectName("labelClasses")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(20, 80, 41, 16))
        self.labelName.setObjectName("labelName")
        self.labelDescription = QtWidgets.QLabel(self.centralwidget)
        self.labelDescription.setGeometry(QtCore.QRect(230, 80, 61, 16))
        self.labelDescription.setObjectName("labelDescription")
        self.filterConcentration = QtWidgets.QComboBox(self.centralwidget)
        self.filterConcentration.setGeometry(QtCore.QRect(880, 100, 71, 21))
        self.filterConcentration.setObjectName("filterConcentration")
        self.filterConcentration.addItem("")
        self.filterConcentration.setItemText(0, "")
        self.filterConcentration.addItem("")
        self.filterConcentration.addItem("")
        self.labelConcentration = QtWidgets.QLabel(self.centralwidget)
        self.labelConcentration.setGeometry(QtCore.QRect(880, 80, 71, 16))
        self.labelConcentration.setObjectName("labelConcentration")
        self.labelRitual = QtWidgets.QLabel(self.centralwidget)
        self.labelRitual.setGeometry(QtCore.QRect(960, 80, 41, 16))
        self.labelRitual.setObjectName("labelRitual")
        self.filterRitual = QtWidgets.QComboBox(self.centralwidget)
        self.filterRitual.setGeometry(QtCore.QRect(960, 100, 71, 21))
        self.filterRitual.setObjectName("filterRitual")
        self.filterRitual.addItem("")
        self.filterRitual.setItemText(0, "")
        self.filterRitual.addItem("")
        self.filterRitual.addItem("")
        self.filterComponents = QtWidgets.QComboBox(self.centralwidget)
        self.filterComponents.setGeometry(QtCore.QRect(1040, 100, 121, 21))
        self.filterComponents.setObjectName("filterComponents")
        self.filterComponents.addItem("")
        self.filterComponents.setItemText(0, "")
        self.filterComponents.addItem("")
        self.filterComponents.addItem("")
        self.filterComponents.addItem("")
        self.filterComponents.addItem("")
        self.labelComponents = QtWidgets.QLabel(self.centralwidget)
        self.labelComponents.setGeometry(QtCore.QRect(1040, 80, 71, 16))
        self.labelComponents.setObjectName("labelComponents")
        self.filterName = QtWidgets.QLineEdit(self.centralwidget)
        self.filterName.setGeometry(QtCore.QRect(20, 100, 161, 20))
        self.filterName.setObjectName("filterName")
        self.buttonName = QtWidgets.QPushButton(self.centralwidget)
        self.buttonName.setGeometry(QtCore.QRect(190, 100, 31, 23))
        self.buttonName.setObjectName("buttonName")
        self.filterDescription = QtWidgets.QLineEdit(self.centralwidget)
        self.filterDescription.setGeometry(QtCore.QRect(230, 100, 161, 20))
        self.filterDescription.setObjectName("filterDescription")
        self.buttonDescription = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDescription.setGeometry(QtCore.QRect(400, 100, 31, 23))
        self.buttonDescription.setObjectName("buttonDescription")
        self.buttonClear = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClear.setGeometry(QtCore.QRect(1170, 100, 91, 23))
        self.buttonClear.setObjectName("buttonClear")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1170, 60, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MongoD&D"))
        self.filterClass.setItemText(1, _translate("MainWindow", "Bard"))
        self.filterClass.setItemText(2, _translate("MainWindow", "Cleric"))
        self.filterClass.setItemText(3, _translate("MainWindow", "Druid"))
        self.filterClass.setItemText(4, _translate("MainWindow", "Paladin"))
        self.filterClass.setItemText(5, _translate("MainWindow", "Ranger"))
        self.filterClass.setItemText(6, _translate("MainWindow", "Sorcerer"))
        self.filterClass.setItemText(7, _translate("MainWindow", "Warlock"))
        self.filterClass.setItemText(8, _translate("MainWindow", "Wizard"))
        self.filterSchool.setItemText(1, _translate("MainWindow", "Abjuration"))
        self.filterSchool.setItemText(2, _translate("MainWindow", "Conjuration"))
        self.filterSchool.setItemText(3, _translate("MainWindow", "Divination"))
        self.filterSchool.setItemText(4, _translate("MainWindow", "Enchantment"))
        self.filterSchool.setItemText(5, _translate("MainWindow", "Evocation"))
        self.filterSchool.setItemText(6, _translate("MainWindow", "Illusion"))
        self.filterSchool.setItemText(7, _translate("MainWindow", "Necromancy"))
        self.filterSchool.setItemText(8, _translate("MainWindow", "Transmutation"))
        self.filterRange.setItemText(1, _translate("MainWindow", "Self"))
        self.filterRange.setItemText(2, _translate("MainWindow", "Touch"))
        self.filterRange.setItemText(3, _translate("MainWindow", "Sight"))
        self.filterRange.setItemText(4, _translate("MainWindow", "Special"))
        self.filterLevel.setItemText(1, _translate("MainWindow", "0"))
        self.filterLevel.setItemText(2, _translate("MainWindow", "1"))
        self.filterLevel.setItemText(3, _translate("MainWindow", "2"))
        self.filterLevel.setItemText(4, _translate("MainWindow", "3"))
        self.filterLevel.setItemText(5, _translate("MainWindow", "4"))
        self.filterLevel.setItemText(6, _translate("MainWindow", "5"))
        self.filterLevel.setItemText(7, _translate("MainWindow", "6"))
        self.filterLevel.setItemText(8, _translate("MainWindow", "7"))
        self.filterLevel.setItemText(9, _translate("MainWindow", "8"))
        self.filterLevel.setItemText(10, _translate("MainWindow", "9"))
        self.labelLevel.setText(_translate("MainWindow", "Level"))
        self.labelRange.setText(_translate("MainWindow", "Range"))
        self.labelSchool.setText(_translate("MainWindow", "School"))
        self.labelClasses.setText(_translate("MainWindow", "Classes"))
        self.labelName.setText(_translate("MainWindow", "Name"))
        self.labelDescription.setText(_translate("MainWindow", "Description"))
        self.filterConcentration.setItemText(1, _translate("MainWindow", "yes"))
        self.filterConcentration.setItemText(2, _translate("MainWindow", "no"))
        self.labelConcentration.setText(_translate("MainWindow", "Concentration"))
        self.labelRitual.setText(_translate("MainWindow", "Ritual"))
        self.filterRitual.setItemText(1, _translate("MainWindow", "yes"))
        self.filterRitual.setItemText(2, _translate("MainWindow", "no"))
        self.filterComponents.setItemText(1, _translate("MainWindow", "no verbal"))
        self.filterComponents.setItemText(2, _translate("MainWindow", "no somatic"))
        self.filterComponents.setItemText(3, _translate("MainWindow", "no material"))
        self.filterComponents.setItemText(4, _translate("MainWindow", "no cost"))
        self.labelComponents.setText(_translate("MainWindow", "Components"))
        self.buttonName.setText(_translate("MainWindow", ">"))
        self.buttonDescription.setText(_translate("MainWindow", ">"))
        self.buttonClear.setText(_translate("MainWindow", "Clear Filters"))
        self.pushButton.setText(_translate("MainWindow", "+ Add Spell"))
        self.label.setText(_translate("MainWindow", "Mongo D&D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

